name: Deploy Backend to EKS

on:
  push:
    branches: [ main ]
   # paths:
    #  - 'src/**'
     # - 'db/**'
      
      # - 'Dockerfile'
      # - 'k8s/**'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_BACKEND: tienda-backend
  ECR_REPOSITORY_DB: tienda-db
  CLUSTER_NAME: devopseks
  NAMESPACE: tienda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest

    - name: Build Database
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG -f db/Dockerfile ./db
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_DB:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_DB:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

    - name: Deploy
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        sed -i "s|{{ECR_URL}}|$ECR_REGISTRY|g" k8s/*.yaml
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/mysql-secret.yaml
        kubectl apply -f k8s/mysql-deployment.yaml
        kubectl apply -f k8s/mysql-service.yaml
        kubectl rollout status deployment/tienda-db -n ${{ env.NAMESPACE }} --timeout=300s
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/backend-hpa.yaml
        kubectl rollout status deployment/tienda-backend -n ${{ env.NAMESPACE }} --timeout=300s
